# Generated by Django 3.0.6 on 2020-06-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='categorie',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='notes.Categorie'),
        ),
    ]
