# Generated by Django 3.0.6 on 2020-10-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Projectid',
            new_name='Project',
        ),
        migrations.AlterField(
            model_name='project',
            name='categorie',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='notes.Categorie'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
