# Generated by Django 3.0.6 on 2020-12-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201005_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(max_length=2048),
        ),
    ]
